Repository CHUCHUDACHUCHU/CampFire_BE, pull requests merged in 2023-01, with the labels that each got.

#3 <FIX> authmiddleware 프론트 요청사항
  backend/src/middlewares/authUser.middleware.js
Labels: enhancement

#4 <FIX> authUser middleware 프론트 요청사항 취소
  .travis.yml
  backend/src/middlewares/authUser.middleware.js
Labels: enhancement

#5 <FEAT> naverLogin with FrontEnd
  backend/src/architecture/controllers/auths.controller.js
  backend/src/architecture/services/auths.service.js
  backend/src/routes/auths.routes.js
Labels: enhancement

#8 <TEST> naverLogin console
  backend/src/architecture/services/auths.service.js
Labels: bug

#9 <FIX> 캠핑장 사이트 상세 조회 API 수정 :memo:
  backend/src/architecture/repositories/camps.repository.js
  backend/src/architecture/services/camps.service.js
Labels: documentation

#10 <FIX> 캠핑장 사이트 상세 조회 API 수정 :memo:
  backend/src/architecture/repositories/camps.repository.js
  backend/src/architecture/services/camps.service.js
Labels: documentation

#11 <FIX> 캠핑장 사이트 상세조회 API 수정 :memo:
  backend/src/architecture/services/camps.service.js
Labels: documentation

#12 <FIX> 캠핑장 사이트 상세조회 API 수정 :memo:
  backend/src/architecture/services/camps.service.js
Labels: documentation

#15 <FEAT> 사이트 검색 기능
  backend/src/architecture/controllers/search.controller.js
  backend/src/architecture/controllers/sites.controller.js
  backend/src/architecture/repositories/books.repository.js
  backend/src/architecture/repositories/search.repository.js
  backend/src/architecture/repositories/sites.repository.js
  backend/src/architecture/services/books.service.js
  backend/src/architecture/services/search.service.js
  backend/src/architecture/services/sites.service.js
  backend/src/migrations/20221231054631-create-sites.js
  backend/src/migrations/20221231054909-create-books.js
  backend/src/models/books.js
  backend/src/models/sites.js
  backend/src/modules/dateModule.js
  backend/src/modules/searchCamps.js
  backend/src/routes/search.route.js
Labels: enhancement

#18 <FEAT> googleLogin 기능 구현
  backend/src/architecture/controllers/auths.controller.js
  backend/src/architecture/services/auths.service.js
  backend/src/routes/auths.routes.js
Labels: enhancement

#19 <FEAT> googleLogin 기능 구현
  backend/src/architecture/controllers/auths.controller.js
  backend/src/architecture/services/auths.service.js
  backend/src/routes/auths.routes.js
Labels: enhancement

#20 <FIX> modify googleLogin axios
  backend/src/architecture/services/auths.service.js
Labels: bug

#24 <FIX> socialLogin double login
  backend/src/architecture/controllers/auths.controller.js
  backend/src/architecture/repositories/auths.repository.js
  backend/src/architecture/services/auths.service.js
Labels: bug

#25 <FIX> socialLogin double login
  backend/src/architecture/controllers/auths.controller.js
  backend/src/architecture/repositories/auths.repository.js
  backend/src/architecture/services/auths.service.js
Labels: bug

#37 <FEAT> sms인증 기능 구현
  backend/package-lock.json
  backend/package.json
  backend/src/architecture/controllers/auths.controller.js
  backend/src/architecture/repositories/auths.repository.js
  backend/src/architecture/services/auths.service.js
  backend/src/architecture/services/hosts.service.js
  backend/src/architecture/services/users.service.js
  backend/src/models/users.js
  backend/src/routes/auths.routes.js
  backend/src/util/auth-encryption.util.js
  docker-compose.yml
Labels: enhancement

#38 <FEAT> sms인증 기능 구현
  backend/package-lock.json
  backend/package.json
  backend/src/architecture/controllers/auths.controller.js
  backend/src/architecture/repositories/auths.repository.js
  backend/src/architecture/services/auths.service.js
  backend/src/architecture/services/hosts.service.js
  backend/src/architecture/services/users.service.js
  backend/src/models/users.js
  backend/src/routes/auths.routes.js
  backend/src/util/auth-encryption.util.js
  docker-compose.yml
Labels: enhancement

#39 <FIX> 문자인증기능 버그 수정
  backend/src/architecture/repositories/auths.repository.js
  backend/src/architecture/services/auths.service.js
Labels: bug
